### ISSUE TITLE
[Bug/Feature] Kitsu.io support

### ISSUE THREAD

**Issue by ghost** [animenotifier/notify.moe#10]
Recently, Hummingbird has changed completely to Kitsu.

**Comment by akyoto** [comment]
Aware of it, thanks :)

Can't give an ETA when I'll be able to do this.
If any other developer wants to implement this please contact me.

**Comment by akyoto** [comment]
In the works right now.

**Comment by akyoto** [comment]
Finished this recently, closing the issue.

notify.moe is using its own anime lists to allow users to increase episode progress in the extension and a Kitsu importer is available now.
