### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by enzobes** [animenotifier/notify.moe#11]
Everyone got the error : 

502 Bad Gateway

nginx/1.10.2

Or its just me ? 

Thanks

**Comment by mrskizzex** [comment]
Everyone, Project is unofficially dead. Nobody can contact Akyoto, for all I know he died horrible and painful death in the abyss of Kyoto University.

**Comment by enzobes** [comment]
Oh shit ! We can always use with localhost ?

**Comment by mrskizzex** [comment]
Sure, but you need to know how to do it. It's not launch&forget type of thing. You need to set up everything yourself. Akyoto wrote a simplified guide in readme.

**Comment by enzobes** [comment]
Ok thanks

**Comment by akyoto** [comment]
Work on ARN 4.0 has begun.
Will update you when I got some stuff to show.

**Comment by akyoto** [comment]
Version 4.0 isn't finished yet but I'll close this because the site is back online.
