### ISSUE TITLE
Calendar Link missing from sidebar

### ISSUE THREAD

**Issue by all-yall** [animenotifier/notify.moe#196]
[Here](https://github.com/animenotifier/notify.moe/commit/97c8f994996268fddb2a782fbd286a71cf2a97e4#r31134978) is where the calendar was deleted from the sidebar. I don't think that this was done on purpose, as the calendar is still accessible via the [url](https://notify.moe/calendar)

**Comment by akyoto** [comment]
[November update notes](https://notify.moe/thread/4Zt5kd-mR)
