### ISSUE TITLE
Activity: Revamp the whole thing

### ISSUE THREAD

**Issue by hazre** [animenotifier/notify.moe#213]
## Right now activity page isn't that useful. That's why I have few suggestions that could improve it:

- Status (Posts where you can talk about anything with markdown support)
- Comments on Status and Activity (comments should be hidden as default and can be seen by clicking on the comments button for a cleaner UI experience)
- Like, Edit*, Comment, Report, Direct link buttons (somehow this exists on profile but not on activity. *only for the user that created the status)
- Better use of white space by introducing a side bar on left side that contains a quick way of updating watching anime and under it recent activities from Forums, Soundtracks, AMV's and etc. (related to #203)
- Anime Activity's should include the poster of the anime for better context instead of only names
- Only show activities that have at least 1* like or comment, for example followers can do that (to reduce the amount of user activities spamming the page. *it can be x numbers but 1 is good for starters)
- Filter to turn off Status/Activities
- Small Airing notices when a new episode of a anime drops it says for example:
 ~ Kakegurui xx - Episode 8 Aired ~ 
(maybe without a frame so it differs from other kind of activities. Also it can be when the simulcast drops instead of actual airing times, maybe a option?)

Inspired by anilist's home design like [here](https://i.imgur.com/2pKJtRb.png)

**Comment by akyoto** [comment]
Status posts exist already (post something on your own profile). Comments on status posts are also available. Activities (on the `/activity` page) are still work in progress, just like many other parts.

The other things you mentioned are all valid points, I'll make separate issues for them once I start working on these.

**Comment by akyoto** [comment]
Closing this particular issue because it focuses on too many features at once and it's hard to assign these to somebody or give it a deadline.
