### ISSUE TITLE
Forum: Automatic github issues

### ISSUE THREAD

**Issue by hazre** [animenotifier/notify.moe#215]
Posts in Suggestions and Bugs section of the forum should automatically create a github issue here for better productivity. (maybe tag it with "from Forum" or something)

_with automatic replies back to the site maybe?_

**Comment by akyoto** [comment]
The problem with this is that GitHub issues are the filtered version of user suggestions.

Users usually don't know how to include technical details - and GitHub, as a place for developers, is meant to be technically concise.

It's fine the way it is, I look at suggestions and create GitHub issues for them if I ever run out of work.
