### ISSUE TITLE
Search: Ignore special characters

### ISSUE THREAD

**Issue by ghost** [animenotifier/notify.moe#222]
Due to the way search is set up, it sometimes acts funky and doesn't show certain anime because the prefix bonus isn't applied because of not typing the necessary special characters in the title.

Example is Howl's Moving Castle:
https://notify.moe/search/howl shows Howl's Moving Castle
https://notify.moe/search/howls doesn't show it
https://notify.moe/search/howls%20moving%20castle does show it

The way to fix this would be ignoring all special characters.

**Comment by akyoto** [comment]
Managed to fix this and also optimize performance in https://github.com/animenotifier/arn/commit/a88294f70dd51f095833c0edcb8ad95400e6c5d1

Search before:
```
BenchmarkAnimeSearch-12             200      10055940 ns/op    10178231 B/op      366607 allocs/op
```

Search after:
```
BenchmarkAnimeSearch-12             200       9648058 ns/op     8059389 B/op      254158 allocs/op
```

[howls](https://notify.moe/search/howls) matches [Howl's Moving Castle](https://notify.moe/anime/CpmTcFmig) now.
