### ISSUE TITLE
The gzip responses appear to be malformed

### ISSUE THREAD

**Issue by soulcramer** [animenotifier/notify.moe#224]
Hello! I was trying to make some request to the API in an Android app and got the following issue https://github.com/square/retrofit/issues/755, https://github.com/square/okhttp/issues/2193

From what I could see from this error it would appear that the responses served are malformed. To verify this, I did the following actions:

I fetched the gzip version of the response I needed with
`wget -S --header="accept-encoding: gzip"  https://notify.moe/api/animelist/VJOK1ckvx`
<details>
<summary>Details</summary>

```bash
--2019-04-21 18:56:12--  https://notify.moe/api/animelist/VJOK1ckvx
Resolving notify.moe (notify.moe)... 165.22.146.88
Connecting to notify.moe (notify.moe)|165.22.146.88|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Access-Control-Allow-Origin: *
  Cache-Control: must-revalidate
  Content-Encoding: gzip
  Content-Type: application/json; charset=utf-8
  Etag: d5fa32c8f86d2416
  Date: Sun, 21 Apr 2019 16:56:08 GMT
  Transfer-Encoding: chunked
Length: unspecified [application/json]
Saving to: ‘VJOK1ckvx.1’
```
</details>

I then tested the gzip, and it appeared that the file was not okay. The error looked like the one I was getting with the Android library I'm using.
`gzip -v -t VJOK1ckvx.1`

```
gzip: VJOK1ckvx.1: unexpected end of file
gzip: VJOK1ckvx.1: uncompress failed
VJOK1ckvx.1:      NOT OK
```

I then downloaded the "json" version of the response
`wget https://notify.moe/api/animelist/VJOK1ckvx`

<details>
<summary>Details</summary>

```bash
--2019-04-21 19:42:36--  https://notify.moe/api/animelist/VJOK1ckvx
Resolving notify.moe (notify.moe)... 165.22.146.88
Connecting to notify.moe (notify.moe)|165.22.146.88|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 245790 (240K) [application/json]
Saving to: ‘VJOK1ckvx.2’
```
</details>

And test it. Here gzip recognized that it wasn't a gzip file.
`gzip -v -t VJOK1ckvx.2`

```
gzip: VJOK1ckvx.2: not in gzip format
VJOK1ckvx.2:      NOT OK
```

I then compressed it with the same compression level that I could infer in gzip.go used in [aero]( https://github.com/aerogo/aero/blob/738e61ca7bd9464d149323ba9f503e3d03f36288/Context.go#L531) 
`gzip VJOK1ckvx.2 --best`

And finally, test this version. This one passed the test.
`gzip -v -t VJOK1ckvx.2.gz`

```
VJOK1ckvx.2.gz:   OK
```

I'm still looking around the code to found what might be causing the problem, this might be a bug from aero but I'm not 100% sure about that.

**Comment by akyoto** [comment]
Chrome seems to gunzip it just fine.

![gzip in Chrome](https://i.imgur.com/wPWemPE.png)

**Comment by akyoto** [comment]
Fixed in https://github.com/aerogo/aero/commit/9e58afd8216963868369b12495ef886a14d6922e
