### ISSUE TITLE
Import: AniList imports seem to be broken

### ISSUE THREAD

**Issue by AnnsAnns** [animenotifier/notify.moe#254]
Context: 
https://discord.com/channels/134910939140063232/134910939140063232/770300262286884874
![image](https://user-images.githubusercontent.com/25822956/97188884-4daa1680-17a4-11eb-88e3-e6f14c560c3e.png)

**Comment by TheHolyLoli** [comment]
Same happens with myanimelist

**Comment by akyoto** [comment]
This has been fixed, closing.
