### ISSUE TITLE
Forum: You can cause unclickable entries by having a 0 character title

### ISSUE THREAD

**Issue by AnnsAnns** [animenotifier/notify.moe#255]
![image](https://user-images.githubusercontent.com/25822956/97215772-30397480-17c5-11eb-9deb-d63acc11b4cf.png)

Expected Result: Either this should be impossible or there should be some other way to access posts when the title is unclickable.

Related Line: https://github.com/animenotifier/notify.moe/blob/29a48d94a5bca208e910ba91b1acb707aad4b580/arn/ThreadAPI.go

**Comment by akyoto** [comment]
The length check for titles exists in `Create` but not in `Edit`.
