### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by akyoto** [animenotifier/notify.moe#33]
Implement a schedule showing a week view where anime from your watching list are displayed.

X axis shows the weekdays and Y axis shows the time when anime get aired.

**Comment by soulcramer** [comment]
Maybe take the view you've done [here](https://notify.moe/calendar) but only with the anime from the watching list?
![image](https://user-images.githubusercontent.com/11772084/33232710-cc550b58-d20a-11e7-8924-b16fc3361e61.png)

**Comment by akyoto** [comment]
Yea I'm playing to add a boolean "Show your entries only" switch maybe in the corner of the UI.

**Comment by soulcramer** [comment]
Since you added it can you close this issue? Unless you plan to improve it?
