### ISSUE TITLE
AnimeListItem: Incremental number input - Plus/Minus signs

### ISSUE THREAD

**Issue by irfan-dahir** [animenotifier/notify.moe#72]
Addition of [+] [-] buttons for number inputs that have incremental change

![Better UX](https://cdn.discordapp.com/attachments/334072779773050892/380824352184336384/ux.png)
otherwise the default browser ones are really tiny
![Default browser](https://cdn.discordapp.com/attachments/334072779773050892/380824566836101123/default.png)

**Comment by akyoto** [comment]
Implemented in abfad585e85270da6c6d6710938ca49699916a53 and e8aed98b3c09e1198319490db7969ad5315ae7c7.
