### ISSUE TITLE
Calendar: Add anime button

### ISSUE THREAD

**Issue by Gworst** [animenotifier/notify.moe#85]
Add "add anime" button to the /calendar  page.

**Comment by soulcramer** [comment]
@blitzprog I'm going to work on this, where do you see the `add anime` button? On the top right like on an anime in the [explore page](https://notify.moe/explore)?

**Comment by akyoto** [comment]
After all, I don't think we'll be able to implement this, the space we are working with is too small.
I don't think people are going to add anime based on title & small icon only.
If people want to add anime from the calendar, they can visit the page.

Most likely won't be implemented in the current calendar design, therefore closing this issue.
