### ISSUE TITLE
Shop: Getting an error 401 from Paypal when buying Gems

### ISSUE THREAD

**Issue by soulcramer** [animenotifier/notify.moe#91]
When trying to order any number of Gems, after validating the transaction in PayPal
![image](https://user-images.githubusercontent.com/11772084/35474882-cf789c58-0394-11e8-9fb4-960ab88e8f6f.png)

The user is getting this error displayed `Error executing PayPal payment (POST https://api.paypal.com/v1/payments/payment/PAY-77R581181E315341FLJWL37Y/execute: 401 )`

**Comment by akyoto** [comment]
Fixed in 8cc80d7e59f4718fffed7cb0c8ebeb2a8d68928f.
